// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.4.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';

abstract class Peer2Peer {
  Future<String> printHello({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPrintHelloConstMeta;

  Future<int> add({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAddConstMeta;

  Future<int> subtract({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSubtractConstMeta;
}

class Peer2PeerImpl implements Peer2Peer {
  final Peer2PeerPlatform _platform;
  factory Peer2PeerImpl(ExternalLibrary dylib) => Peer2PeerImpl.raw(Peer2PeerPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory Peer2PeerImpl.wasm(FutureOr<WasmModule> module) => Peer2PeerImpl(module as ExternalLibrary);
  Peer2PeerImpl.raw(this._platform);
  Future<String> printHello({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_print_hello(port_),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kPrintHelloConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPrintHelloConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "print_hello",
        argNames: [],
      );

  Future<int> add({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_add(port_, arg0, arg1),
      parseSuccessData: _wire2api_i32,
      parseErrorData: null,
      constMeta: kAddConstMeta,
      argValues: [
        a,
        b
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAddConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "add",
        argNames: [
          "a",
          "b"
        ],
      );

  Future<int> subtract({required int a, required int b, dynamic hint}) {
    var arg0 = api2wire_i32(a);
    var arg1 = api2wire_i32(b);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_subtract(port_, arg0, arg1),
      parseSuccessData: _wire2api_i32,
      parseErrorData: null,
      constMeta: kSubtractConstMeta,
      argValues: [
        a,
        b
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSubtractConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "subtract",
        argNames: [
          "a",
          "b"
        ],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_i32(int raw) {
  return raw;
}
// Section: finalizer
