name: peer2peer
description: A starting point for Dart libraries or applications.
version: 0.0.1+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.4
  # path: ^1.8.0

dependency_overrides:
  ffigen: 9.0.1

dev_dependencies:
  ffigen: ^10.0.0
  lints: ^2.1.0
  test: ^1.24.0
