[package]
name = "peer2peer"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]
path = "src/lib.rs"

#[[bin]]
#name = "peer2peer_bin"
#path = "src/_bin"

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"
walkdir = { version = "2.4.0", features = [] }
cc = "1.0.69"

[dependencies]
flutter_rust_bridge = "1.82.*"
libp2p = { version = "0.53.1", features = [
    "tokio",
    "gossipsub",
    "mdns",
    "noise",
    "macros",
    "tcp",
    "yamux",
    "quic",
    "ping",
] }
tokio = { version = "1.34", features = ["full"] }
futures = "0.3.29"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0.75"
system-configuration = "0.5.1"

# logs
lazy_static = "1.4.0"
log = "0.4.17"
simplelog = "0.12.0"
parking_lot = "0.12.1"

[dev-dependencies]
